### ISSUE TITLE
About the MHD

### ISSUE THREAD

**Issue by gangli95** [josedolz/LiviaNET#17]
Hi,Jose.
Recently, I counted the Dice and HD, and Dices can reach 0.9, but HD is around 3 or 4, which is so different with your result. What are the  differences between HD and MHD, and is there anything I need to do when I count HD?

**Comment by josedolz** [comment]
Hi @gangli95 

The standard HD takes into account the distances from all the points in both contours. On the other hand, the modified HD takes only the 95% of the computed distances, putting aside some outliers. That is why the values of MHD are typically smaller than HD values.

**Comment by gangli95** [comment]
Hi,Jose
![image](https://user-images.githubusercontent.com/33647715/39975968-0111e3be-5764-11e8-9d49-85fc6d2fea2a.png)
I found this equation in M.-P. Dubuisson's [paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=576361), did you use this to count the MHD

**Comment by gangli95** [comment]
Hi,Jose
![image](https://user-images.githubusercontent.com/33647715/39976765-fc442c9e-5767-11e8-8604-853dc86d6c95.png)

I found this equation in Dubuisson's [paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=576361), did you takes the 95%  of the computed distances and then count the mean of the 95%  of the computed distances?

**Comment by josedolz** [comment]
Hi @gangli95 

sorry for my late answer, I have been quite busy the last months.

Here is a piece of code to compute the MHD (evaluation.py):

[https://github.com/hjkuijf/MRBrainS18](https://github.com/hjkuijf/MRBrainS18)

**Comment by gangli95** [comment]
Hi, @Jose
It's so kind of you to give me this reply, and it will never  be late for the answers.  I'll read the code carefully.
Thanks very much!
