### ISSUE TITLE
Directory structure for multiple modalities.

### ISSUE THREAD

**Issue by mbrown0294** [josedolz/LiviaNET#21]
Hello,

I have been trying to run your algorithm on some nifti data that I have, but have been getting 
`ValueError: could not broadcast input array from shape (0,0,0) into shape (1,25,25,25)`
Is this maybe because of the format of my image files? I have multiple modalities, and am not sure how to handle that (your image files appear to only have one image per subject). This is my current file setup:

train/
----| MR/
--------| flair_0.nii.gz
--------| flair_1.nii.gz
--------| flair_2.nii.gz
--------| t1_0.nii.gz
--------| t1_1.nii.gz
--------| t1_2.nii.gz
----| Label/
----| ROI/
with Label and ROI having the same structure, but prefixed with "label" and "ROI" respectively. Is this how I should be handling modalities?

**Comment by josedolz** [comment]
Hi @mbrown0294 

This version is designed to only employ one image modality as input. Nevertheless, having multiple modalities will not affect the running of the algorithm (i.e., you should be able to run the training). From what I see I think the error comes from the code being unable to find the ROI when sampling the sub-patches. Just verify that the paths are properly defined and that 'getSamplesSubject' and 'load_imagesSinglePatient' functions ([in this file](https://github.com/josedolz/LiviaNET/blob/master/src/LiviaNet/Modules/IO/sampling.py)) can access to all the images.

Jose

**Comment by mbrown0294** [comment]
Hi,

I have confirmed that both functions are able to access the correct files, and I know that I used type 0 for NIFTI. I still get this error on the very first file passed through the sampling.py function: 
```
Traceback (most recent call last):
  File "./src/networkTraining.py", line 82, in <module>
    networkTraining(sys.argv[1:])
  File "./src/networkTraining.py", line 77, in networkTraining
    startTraining(networkModelName,configIniName)
  File "./src/LiviaNet/startTraining.py", line 137, in startTraining
    applyPadding
  File "./src/LiviaNet/Modules/IO/sampling.py", line 87, in getSamplesSubepoch
    receptiveField
  File "./src/LiviaNet/Modules/IO/sampling.py", line 193, in getSamplesSubject
    imageSample[:1] = imgSubject[ xMin:xMax,yMin:yMax,zMin:zMax]
ValueError: could not broadcast input array from shape (0,0,0) into shape (1,25,25,25)
```

**Comment by josedolz** [comment]
Hi @mbrown0294 Can you send me your config file and your data (at least the 6 images you show in the folders) so that I can check which is the problem?

**Comment by mbrown0294** [comment]
I believe the issue was how I labeled my folders. My ROI and Label were switched somehow. Thank you for the help!
