### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by HongyiDuanmu26** [josedolz/LiviaNET#22]
Hi Jose,

Thanks you so much for your repo and it is really good. May I ask what visualization tool you used for the 3D image in the main page, it is quite fancy.

**Comment by josedolz** [comment]
Hi @HongyiDuanmu26 

For that specific example I used [MITK](http://mitk.org/wiki/Downloads). You can also use [3DSlicer](https://www.slicer.org).

Jose
