### ISSUE TITLE
how did you got the GT?

### ISSUE THREAD

**Issue by maximedieudonne** [josedolz/LiviaNET#27]
Hi Jose,
The GT are available only on .mat without header, Could you please give me some information about the GT ? how did you made them for exemple ?

Best regards,

Maxime dieudonné

**Comment by josedolz** [comment]
Hi @MaximeDdnn 

This is explained in the paper. For IBSR, images are provided with their corresponding GT. For the ABIDE dataset, we employed FreeSurfer to generate the masks.

Jose

**Comment by maximedieudonne** [comment]
thank you for your quick answer! :)
the five images MR_Imgx with thier corresponding Label and GT are from IBSR ? I thougth it was from ABIDE and you make the GT manualy

**Comment by josedolz** [comment]
No, the few subjects shared (as .mat files) are from ABIDE and the corresponding GTs are obtained with Freesurfer. We didn't perform manual segmentations on any MRI image.

**Comment by maximedieudonne** [comment]
thank you for the information
