### ISSUE TITLE
Transfer code to py3

### ISSUE THREAD

**Issue by gangli95** [josedolz/LiviaNET#8]
py2 stopped upgrading, and have you try to transfer code to py3?

**Comment by josedolz** [comment]
Hi @gangli95 I use to work on python 2. I have not considered yet to move the code to python3, but maybe I'll do it in some point. 

Thanks for the suggestion.

Jose.

**Comment by gangli95** [comment]
Hi, thanks for your reply!

This project is great, and actually I am considering to move your code to
python3 and try to do some optimization. I'd appreciate it if you can give
me the permission.

Thanks.

Gang.

2017年11月14日星期二，Jose Dolz <notifications@github.com> 写道：

**Comment by josedolz** [comment]
Sure! When I share my work the idea is that others can use it. So feel free to add/modify whatever you want to satisfy your needs. Just do not forget to mention my work when you use it elsewhere. :)

Jose

**Comment by gangli95** [comment]
Great! Thanks for your work again and it will never be forgotten.

Gang

2017年11月14日星期二，Jose Dolz <notifications@github.com> 写道：

**Comment by josedolz** [comment]
Ok, thanks.

Good luck and let me know something if you need some assistance.

Jose
